// menu for restaurant
import React from 'react';
import ramen from '../assets/images/ramen_image.jpg';
import okonomi from '../assets/images/okonomi-1.jpg';
import '../assets/css/menu.css';
import FoodCard from '../components/FoodCard';
import doraemon from '../assets/images/Doraemon.jpg';
import gyoza from '../assets/images/gyoza.jpg'

const Menu = () => {

    return (
    <>
        <div className="menu-container">
            <div className="food-card-container">
                <FoodCard
                    image={ramen}
                    title="難波ラーメン"
                    price="$1020"
            />
                <FoodCard
                    image={doraemon}
                    title="難波焼き"
                    price="$2345234530"
                />
                <FoodCard
                    image={ramen}
                    title="難波ラーメン"
                    price="$20"
                />
                <FoodCard
                    image={doraemon}
                    title="難波焼き"
                    price="$2345234530"
                />
                <FoodCard
                    image={ramen}
                    title="難波ラーメン"
                    price="$20"
                />
                <FoodCard
                    image={doraemon}
                    title="難波焼き"
                    price="$2345234530"
                />
                <FoodCard
                    image={ramen}
                    title="難波ラーメン"
                    price="$20"
                />
                <FoodCard
                    image={doraemon}
                    title="難波焼き"
                    price="$2345234530"
                />
                <FoodCard
                    image={ramen}
                    title="難波ラーメン"
                    price="$20"
                />
                <FoodCard
                    image={doraemon}
                    title="難波焼き"
                    price="$2345234530"
                />
                <FoodCard
                    image={ramen}
                    title="難波ラーメン"
                    price="$20"
                />
                <FoodCard
                    image={doraemon}
                    title="難波焼き"
                    price="$2345234530"
                />
                <FoodCard
                    image={ramen}
                    title="難波ラーメン"
                    price="$20"
                />
                <FoodCard
                    image={doraemon}
                    title="難波焼き"
                    price="$2345234530"
                />
                <FoodCard
                    image={ramen}
                    title="難波ラーメン"
                    price="$20"
                />
                <FoodCard
                    image={doraemon}
                    title="難波焼き"
                    price="$2345234530"
                />
                <FoodCard
                    image={ramen}
                    title="難波ラーメン"
                    price="$20"
                />
                <FoodCard
                    image={doraemon}
                    title="難波焼き"
                    price="$2345234530"
                />
                <FoodCard
                    image={ramen}
                    title="難波ラーメン"
                    price="$20"
                />
                <FoodCard
                    image={doraemon}
                    title="難波焼き"
                    price="$2345234530"
                />
                <FoodCard
                    image={ramen}
                    title="難波ラーメン"
                    price="$20"
                />
                <FoodCard
                    image={doraemon}
                    title="難波焼き"
                    price="$2345234530"
                />
                <FoodCard
                    image={ramen}
                    title="難波ラーメン"
                    price="$20"
                />
                <FoodCard
                    image={doraemon}
                    title="難波焼き"
                    price="$2345234530"
                />
                <FoodCard
                    image={ramen}
                    title="難波ラーメン"
                    price="$20"
                />
                <FoodCard
                    image={doraemon}
                    title="難波焼き"
                    price="$2345234530"
                />
                <FoodCard
                    image={ramen}
                    title="難波ラーメン"
                    price="$20"
                />
                <FoodCard
                    image={doraemon}
                    title="難波焼き"
                    price="$2345234530"
                />
                <FoodCard
                    image={ramen}
                    title="難波ラーメン"
                    price="$20"
                />
                <FoodCard
                    image={doraemon}
                    title="難波焼き"
                    price="$2345234530"
                />
                <FoodCard
                    image={ramen}
                    title="難波ラーメン"
                    price="$20"
                />
                <FoodCard
                    image={doraemon}
                    title="難波焼き"
                    price="$2345234530"
                />
                <FoodCard
                    image={ramen}
                    title="難波ラーメン"
                    price="$20"
                />
                <FoodCard
                    image={doraemon}
                    title="難波焼き"
                    price="$2345234530"
                />
                <FoodCard
                    image={ramen}
                    title="難波ラーメン"
                    price="$20"
                />
                <FoodCard
                    image={doraemon}
                    title="難波焼き"
                    price="$2345234530"
                />
                <FoodCard
                    image={ramen}
                    title="難波ラーメン"
                    price="$20"
                />
                <FoodCard
                    image={gyoza}
                    title="難波gyoza"
                    price="$0"
                />
                <FoodCard
                    image={ramen}
                    title="難波ラーメン"
                    price="$20"
                />
                <FoodCard
                    image={okonomi}
                    title="難波お好み焼き"
                    price="$30"
                />
            </div>
        </div>
    </>
    );
}

export default Menu;
